In [1]:
import torch

X Matrisimiz

In [2]:
x = torch.tensor([1,2,3,4,5,6]).reshape(-1,3).float()
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Sigmoid Fonksiyonumuz

In [3]:
# $f(x) = \frac{1}{1 + exp(-x)}$

def sigmoid_activation(x):
  return 1 / (1 + torch.exp(-x))

Tanh Fonksiyonumuz

In [4]:
# $f(x) = \frac{exp(x) - exp(-x)}{exp(x) + exp(-x)}$
def tanh_function(x):
    return ((torch.exp(x)-torch.exp(-x))/(torch.exp(x)+torch.exp(-x)))

Seed değerimiz = 1

In [10]:
torch.manual_seed(1)
weight1 = torch.randn(50, 3) 
bias1 = torch.randn(50, 1) 

weight2 = torch.randn(1,50)
bias2 = torch.randn(1, 1)

h1 = tanh_function(torch.matmul(weight1,x.T)+bias1)
o1 = sigmoid_activation(torch.matmul(weight2,h1)+bias2)

print(o1)

tensor([[0.3414, 0.4518]])


Seed değerimiz = Öğrenci Numaram = 190401015

In [11]:
torch.manual_seed(190401015)
weight1 = torch.randn(50, 3) 
bias1 = torch.randn(50, 1) 

weight2 = torch.randn(1,50)
bias2 = torch.randn(1, 1)

h1 = tanh_function(torch.matmul(weight1,x.T)+bias1)
o1 = sigmoid_activation(torch.matmul(weight2,h1)+bias2)

print(o1)

tensor([[0.5657, 0.9995]])
